"""The ONE layout table and the dump/unit-file plumbing every tool shares.

Engine facts (hard limits) live here.  Policy thresholds (budget tiers, slack floors,
warning levels) live in PROJECT.md section 4 and are read by read_project_numbers().
"""
import json
import os
import re
from collections import OrderedDict

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def path(*p):
    return os.path.join(ROOT, *p)


# ---------------------------------------------------------------- engine limits
BOX_COLS = 28            # message box: renderer wraps at 0x38 bytes = 28 full-width columns
BOX_ROWS = 4             # 0x41F6A0: the 4th line break fills the box
SCENE_COLS = 28          # subtitles: assumed equal to the box until tested in game (FLAGS)
SCENE_ROWS = 4
CHOICE_COLS = 28         # choice options: assumed until tested in game (FLAGS)
SCR_MAX_BYTES = 0xFFFF   # every offset in a script header is u16
SCR_MAX_TOKENS = 1499    # token pages 1..250, FB..FF x 250
UNIT_MAX_MESSAGES = 60   # a unit holds at most this many messages (script) or subtitles (scene)

STORES = ('script', 'scene', 'system')
DUMP_FILE = {s: path('dumps', '%s.tsv' % s) for s in STORES}
LAYOUT_FILE = path('dumps', 'layout.json')
ORIGINALS_FILE = path('dumps', 'originals.json')
TL_DIR = path('tl')

DUMP_HEADER = {
    'script': ['# Abyss Boat - script store: room scripts (SCRIPT.PAK *.SCR).',
               '# Generated by `python3 tools/assemble.py refresh`. Never edit by hand.',
               '# columns: id <TAB> context <TAB> source',
               '# context: msg|choice|text, spk=N speaker slot in this file (- unknown),',
               '#          "+" = continues the previous message in the same box'],
    'scene': ['# Abyss Boat - scene store: cutscene subtitles (SCRIPT.PAK *.SCE).',
              '# Generated by `python3 tools/assemble.py refresh`. Never edit by hand.',
              '# columns: id <TAB> context <TAB> source',
              '# context: sub START-END (frames, 30 fps)'],
    'system': ['# Abyss Boat - system store: UI strings inside AbyssBoat.exe.',
               '# Generated by `python3 tools/assemble.py refresh`. Never edit by hand.',
               '# columns: id <TAB> context <TAB> source',
               '# context: fw slot=N  (full-width: 2 bytes per character, 1 per {br}; N bytes)',
               '#          ascii slot=N (plain ASCII, N bytes)'],
}


class Row:
    __slots__ = ('id', 'ctx', 'src', 'tgt', 'line')

    def __init__(self, id, ctx, src, tgt='', line=0):
        self.id, self.ctx, self.src, self.tgt, self.line = id, ctx, src, tgt, line

    @property
    def file(self):
        return self.id.split('/')[0]


def read_dump(store):
    rows = []
    with open(DUMP_FILE[store], encoding='utf-8') as f:
        for n, line in enumerate(f, 1):
            line = line.rstrip('\n').rstrip('\r')
            if not line or line.startswith('#'):
                continue
            parts = line.split('\t')
            if len(parts) != 3:
                raise ValueError('%s:%d: expected 3 columns' % (DUMP_FILE[store], n))
            rows.append(Row(parts[0], parts[1], parts[2], line=n))
    return rows


def write_dump(store, rows):
    with open(DUMP_FILE[store], 'w', encoding='utf-8', newline='\n') as f:
        for h in DUMP_HEADER[store]:
            f.write(h + '\n')
        for r in rows:
            f.write('%s\t%s\t%s\n' % (r.id, r.ctx, r.src))


def load_layout():
    with open(LAYOUT_FILE, encoding='utf-8') as f:
        return json.load(f)


# ---------------------------------------------------------------- units

SYSTEM_UNITS = OrderedDict([
    ('menus', ('options', 'equip', 'camp', 'decks')),
    ('rooms', ('rooms',)),
    ('items', ('items',)),
    ('hints', ('hints',)),
    ('errors', ('misc',)),
])
SCENE_GROUP = re.compile(r'^(SCN\d+|EPILOG|OP)')

# Dispatch order (PROJECT.md section 2).  The ship is capsized and the party works its way
# down from the bar on deck 4.  A file's deck is its prefix (NO4_BAR -> NO4); the '_T' files
# are prototype/test scripts (FLAGS F-008) and form a deck of their own, dispatched last.
DECK_ORDER = ('NO4', 'NO5', 'NO6', 'NO3', 'NO2', 'NO1', 'SPACESHIP', 'NO4_T')


def deck_of(f):
    return f.split('_')[0] + ('_T' if f.endswith('_T') else '')


def scene_order(group):
    """Story order of a scene group: OP, SCNnnn by number, EPILOG."""
    if group == 'OP':
        return (0, 0, '')
    if group.startswith('SCN'):
        return (1, int(group[3:]), '')
    if group == 'EPILOG':
        return (2, 0, '')
    return (3, 0, group)


def _messages(rows):
    return sum(1 for r in rows if r.ctx.startswith('msg'))


def _bundle(groups, size):
    """Pack whole groups (lists of rows) into bundles of <= UNIT_MAX_MESSAGES by `size`,
    as few as the cap allows and filled to about the same size.  -> list of lists of groups."""
    total = sum(size(g) for g in groups)
    target = -(-total // max(1, -(-total // UNIT_MAX_MESSAGES)))
    out, cur, n = [], [], 0
    for g in groups:
        if cur and (n + size(g) > UNIT_MAX_MESSAGES or n >= target):
            out.append(cur)
            cur, n = [], 0
        cur.append(g)
        n += size(g)
    if cur:
        out.append(cur)
    return out


def _split_parts(rows):
    """Split one script file's rows into parts of <= UNIT_MAX_MESSAGES messages,
    cutting only where the next message does not continue the previous box."""
    msgs = [r for r in rows if r.ctx.startswith('msg')]
    other = [r for r in rows if not r.ctx.startswith('msg')]
    if len(msgs) <= UNIT_MAX_MESSAGES:
        return [rows]
    nparts = -(-len(msgs) // UNIT_MAX_MESSAGES)
    target = -(-len(msgs) // nparts)
    parts, cur = [], []
    for r in msgs:
        if len(cur) >= target and not r.ctx.endswith('+'):
            parts.append(cur)
            cur = []
        cur.append(r)
    parts.append(cur)
    parts[0] = parts[0] + other
    return parts


def units(store, rows=None):
    """OrderedDict unit_name -> rows, in dispatch order (PROJECT.md section 2).

    script: per deck (DECK_ORDER), first every file over UNIT_MAX_MESSAGES messages as
            parts <FILE>.pNN, then the deck's other files packed whole, in dump order, into
            bundles <DECK>.bNN of <= UNIT_MAX_MESSAGES messages.
    scene:  cutscene groups (SCN038 = SCN038A, B, D, _5C1, _5C2) in story order, packed
            whole into bundles of <= UNIT_MAX_MESSAGES subtitles, named by their span
            (OP-SCN034) or by the group when it is alone.
    system: one unit per table group (SYSTEM_UNITS)."""
    rows = read_dump(store) if rows is None else rows
    out = OrderedDict()
    if store == 'script':
        decks = OrderedDict((d, OrderedDict()) for d in DECK_ORDER)
        for r in rows:
            decks.setdefault(deck_of(r.file), OrderedDict()).setdefault(r.file, []).append(r)
        for deck, files in decks.items():
            small = []
            for f, rs in files.items():
                if _messages(rs) > UNIT_MAX_MESSAGES:
                    for k, p in enumerate(_split_parts(rs), 1):
                        out['%s.p%02d' % (f, k)] = p
                else:
                    small.append(rs)
            for k, b in enumerate(_bundle(small, _messages), 1):
                out['%s.b%02d' % (deck, k)] = [r for rs in b for r in rs]
    elif store == 'scene':
        groups = OrderedDict()
        for r in rows:
            m = SCENE_GROUP.match(r.file)
            groups.setdefault(m.group(1) if m else r.file, []).append(r)
        names = sorted(groups, key=scene_order)
        for b in _bundle([groups[g] for g in names], len):
            first, last = b[0][0].file, b[-1][0].file
            gf = SCENE_GROUP.match(first)
            gl = SCENE_GROUP.match(last)
            first = gf.group(1) if gf else first
            last = gl.group(1) if gl else last
            out[first if first == last else '%s-%s' % (first, last)] = [r for g in b for r in g]
    else:
        table_unit = {t: u for u, ts in SYSTEM_UNITS.items() for t in ts}
        for u in SYSTEM_UNITS:
            out[u] = []
        for r in rows:
            out[table_unit[r.file]].append(r)
    return out


def unit_path(store, unit):
    return os.path.join(TL_DIR, store, unit + '.tsv')


def unit_header(store, unit, rows):
    h = ['# unit: %s/%s' % (store, unit),
         '# rows: %d' % len(rows),
         '# columns: id <TAB> context <TAB> source <TAB> target (empty target = untranslated)']
    return h


def read_unit_file(p):
    """-> (header_lines, rows, problems)"""
    header, rows, problems = [], [], []
    with open(p, encoding='utf-8') as f:
        for n, line in enumerate(f, 1):
            line = line.rstrip('\n').rstrip('\r')
            if line.startswith('#'):
                header.append(line)
                continue
            if not line.strip():
                continue
            parts = line.split('\t')
            if len(parts) == 3:
                parts.append('')
            if len(parts) != 4:
                problems.append('%s:%d: expected 4 tab-separated columns, found %d'
                                % (p, n, len(parts)))
                continue
            rows.append(Row(parts[0], parts[1], parts[2], parts[3], line=n))
    return header, rows, problems


def all_unit_files():
    """-> list of (store, unit, path) for every file under tl/."""
    out = []
    for store in STORES:
        d = os.path.join(TL_DIR, store)
        if not os.path.isdir(d):
            continue
        for fn in sorted(os.listdir(d)):
            if fn.endswith('.tsv'):
                out.append((store, fn[:-4], os.path.join(d, fn)))
    return out


def translations():
    """-> dict (store, id) -> target for every non-empty target under tl/."""
    out = {}
    for store, unit, p in all_unit_files():
        _, rows, _ = read_unit_file(p)
        for r in rows:
            if r.tgt.strip():
                out[(store, r.id)] = r.tgt
    return out


# ---------------------------------------------------------------- PROJECT.md numbers

def read_project_numbers():
    """Parse PROJECT.md section 4.  Returns dict with keys present (floats), missing keys
    absent.  Recognised: slack_floor, reserve, floor, tiers {name: (lo, hi)},
    blocked_stores {store: reason} (the "Stores blocked whole" row: every unit of the
    store is blocked whatever its ratio, e.g. pending an engine patch)."""
    out = {'tiers': {}}
    try:
        text = open(path('PROJECT.md'), encoding='utf-8').read()
    except OSError:
        return out
    sec = re.search(r'^## 4\. Budget(.*?)^## 5\.', text, re.S | re.M)
    if not sec:
        return out
    body = sec.group(1)

    def num(s):
        m = re.search(r'(\d[\d,]*(?:\.\d+)?)', s.replace('«FILL»', ''))
        return float(m.group(1).replace(',', '')) if m else None
    for line in body.splitlines():
        cells = [c.strip() for c in line.strip().strip('|').split('|')]
        if len(cells) < 2:
            continue
        key = cells[0].lower()
        if 'slack floor' in key:
            out['slack_floor'] = num(cells[1])
        elif 'reserve kept per container' in key:
            out['reserve'] = num(cells[1])
        elif 'measured floor' in key:
            out['floor'] = num(cells[1])
        elif 'stores blocked whole' in key:
            flag = re.search(r'F-\d+', cells[1])
            out['blocked_stores'] = {s: flag.group(0) if flag else 'see PROJECT.md section 4'
                                     for s in STORES if re.search(r'\b%s\b' % s, cells[1])}
        elif key in ('blocked', 'a', 'b', 'c', 'd'):
            nums = re.findall(r'\d+(?:\.\d+)?', cells[1].replace('«FILL»', ''))
            if nums:
                out['tiers'][key] = tuple(float(x) for x in nums)
    return {k: v for k, v in out.items() if v is not None}
